// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fastfabric-extensions/remote/storage/storage.proto

package remote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/hyperledger/fabric/protos/common"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StorageRequest struct {
	Block                *common.Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ChannelId            string        `protobuf:"bytes,2,opt,name=channelId,proto3" json:"channelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StorageRequest) Reset()         { *m = StorageRequest{} }
func (m *StorageRequest) String() string { return proto.CompactTextString(m) }
func (*StorageRequest) ProtoMessage()    {}
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74090f2be8230015, []int{0}
}

func (m *StorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequest.Unmarshal(m, b)
}
func (m *StorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequest.Marshal(b, m, deterministic)
}
func (m *StorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequest.Merge(m, src)
}
func (m *StorageRequest) XXX_Size() int {
	return xxx_messageInfo_StorageRequest.Size(m)
}
func (m *StorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequest proto.InternalMessageInfo

func (m *StorageRequest) GetBlock() *common.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *StorageRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_74090f2be8230015, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StorageRequest)(nil), "remote.StorageRequest")
	proto.RegisterType((*Result)(nil), "remote.Result")
}

func init() {
	proto.RegisterFile("fastfabric-extensions/remote/storage/storage.proto", fileDescriptor_74090f2be8230015)
}

var fileDescriptor_74090f2be8230015 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x4f, 0xbd, 0x4e, 0x84, 0x40,
	0x10, 0x16, 0x93, 0x23, 0xde, 0x9c, 0x5e, 0xb1, 0x85, 0xb9, 0x10, 0x0b, 0x82, 0x0d, 0x8d, 0x4b,
	0xc4, 0xc6, 0x5a, 0x2b, 0x13, 0x0b, 0xb3, 0x3c, 0xc1, 0xb2, 0x0c, 0x48, 0x84, 0x1d, 0xdd, 0x1d,
	0x12, 0xe3, 0xd3, 0x1b, 0x58, 0xd4, 0xd8, 0x5d, 0xf5, 0xe5, 0xfb, 0x9b, 0x1f, 0x28, 0x5b, 0xed,
	0xb9, 0xd5, 0xb5, 0xeb, 0xcd, 0x0d, 0x7e, 0x32, 0x5a, 0xdf, 0x93, 0xf5, 0x85, 0xc3, 0x91, 0x18,
	0x0b, 0xcf, 0xe4, 0x74, 0xf7, 0x8b, 0xf2, 0xdd, 0x11, 0x93, 0x88, 0x83, 0x9b, 0x24, 0x0b, 0xf5,
	0x85, 0xa1, 0x71, 0x24, 0xbb, 0x42, 0xc8, 0x64, 0x15, 0xec, 0xab, 0x50, 0x52, 0xf8, 0x31, 0xa1,
	0x67, 0x71, 0x0d, 0x9b, 0x7a, 0x20, 0xf3, 0x76, 0x88, 0xd2, 0x28, 0xdf, 0x95, 0x17, 0x72, 0xcd,
	0x3f, 0xcc, 0xa2, 0x0a, 0x9e, 0xb8, 0x82, 0xad, 0x79, 0xd5, 0xd6, 0xe2, 0xf0, 0xd4, 0x1c, 0x4e,
	0xd3, 0x28, 0xdf, 0xaa, 0x3f, 0x21, 0x3b, 0x83, 0x58, 0xa1, 0x9f, 0x06, 0x2e, 0xbf, 0x60, 0xb7,
	0x8e, 0x7f, 0x41, 0x74, 0xe2, 0x16, 0x36, 0x33, 0x45, 0x71, 0x29, 0xc3, 0x6d, 0xf2, 0xff, 0xf2,
	0x64, 0xff, 0xa3, 0x87, 0x7e, 0x76, 0x22, 0xee, 0xe1, 0xfc, 0xd1, 0xa1, 0x66, 0x7c, 0xc6, 0xa6,
	0x43, 0x77, 0x7c, 0xb3, 0x8e, 0x97, 0x0f, 0xef, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x90, 0x84,
	0x99, 0xe5, 0x3b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoragePeerClient is the client API for StoragePeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoragePeerClient interface {
	Store(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*Result, error)
	CreateLedger(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*Result, error)
}

type storagePeerClient struct {
	cc *grpc.ClientConn
}

func NewStoragePeerClient(cc *grpc.ClientConn) StoragePeerClient {
	return &storagePeerClient{cc}
}

func (c *storagePeerClient) Store(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) CreateLedger(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/CreateLedger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoragePeerServer is the server API for StoragePeer service.
type StoragePeerServer interface {
	Store(context.Context, *StorageRequest) (*Result, error)
	CreateLedger(context.Context, *StorageRequest) (*Result, error)
}

func RegisterStoragePeerServer(s *grpc.Server, srv StoragePeerServer) {
	s.RegisterService(&_StoragePeer_serviceDesc, srv)
}

func _StoragePeer_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).Store(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_CreateLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).CreateLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/CreateLedger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).CreateLedger(ctx, req.(*StorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoragePeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.StoragePeer",
	HandlerType: (*StoragePeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _StoragePeer_Store_Handler,
		},
		{
			MethodName: "CreateLedger",
			Handler:    _StoragePeer_CreateLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fastfabric-extensions/remote/storage/storage.proto",
}
